# This config is used to determine the order in which servers are tested, and optionally to exclude specific servers.

# 'exclude-servers' is a string array of server names to skip during version comparison.
# Example: ["server1", "server2"]
# Note: Spaces outside the strings will be ignored.
exclude-servers = []

# 'order-mode' defines how the server list should be ordered (case-insensitive).
# Options:
#   "DEFAULT" - servers will be checked in alphabetical order
#   "CUSTOM"  - use the order defined in 'server-list'
order-mode = "DEFAULT"

# 'server-list' is used only if order-mode is set to "CUSTOM".
# It's recommended to list all your servers here and manage exclusions separately using 'exclude-servers',
# but including only specific servers is also possible.
server-list = []

# 'first-match' determines whether the first or last matching server should be used.
# Set to true to use the first match found, false to use the last.
first-match = true

# If enabled this option ensures that whenever a client is kicked from a server (whether during login, via /kick, or for another reason),
# they will be automatically redirected (bounced) to another server instead of being disconnected.
enable-fallback-bouncing = true
# If set to true, the server the client was kicked from will be temporarily excluded from fallback options,
# preventing the client from being sent back there during fallback-bouncing.
exclude-previous-server = false
# When there is a valid server name in 'explicit-fallback-server' the plugin won't search for a new server and instead only tries the specified server.
# Leave this empty, if you'd like to diable this option (also this is disabled when enable-fallback-bouncing is set to false).
explicit-fallback-server = ""

# an [explicit-routing] option will be added in the future, with which the plugin will no longer automatically look for a matching server but takes a static routing map provided through the config
