# This config is used to determine how and if servers are checked for their protocol versions whenevery a client logs in (and optionally if they lost connection)

# 'whitelist' is a string array of server names to check for their protocol version when a client tries to connect.
# leaving this empty is equal to putting all registered servers in
# Example: ["server1", "server2"]
# Note: Spaces outside the strings will be ignored.
whitelist = []

# 'blacklist' is an array of strings to exclude from the temporary list of servers during version comparison.
# first the whitelist is added and then all servers contained in the blacklist are removed from that temporary list.
blacklist = []

# If enabled this option ensures that joining players will be distributed evenly over all servers
# Options: (case-insensitive)
#   "FIRST-MATCH" - players will be sent to the first matching server
#   "BALANCED" - players will be evenly distributed on all matches in the order deriving from 'order-mode'
distribution = "FIRST-MATCH"

# If enabled this option ensures that whenever a client is kicked from a server (whether during login, via /kick, or for another reason),
# they will be automatically redirected (bounced) to another server instead of being disconnected. (obviously if a client disconnects explicitly via leaving the server they will not be redirected)
enable-fallback-bouncing = true
# If set to true, the server the client was kicked from will be temporarily excluded from fallback options,
# preventing the client from being sent back there during fallback-bouncing.
exclude-previous-server = false
# When there is a valid server name in 'explicit-fallback-server' the plugin won't search for a new server and instead only tries the specified server.
# Leave this empty, if you'd like to disable this option (also this is disabled when enable-fallback-bouncing is set to false).
explicit-fallback-server = ""


###### the following options are not yet (fully) implemented

# This option will determine how the plugin handles servers which can't be found
# Options: (case-insensitive)
#   "NEXT-LEVEL" - if the last attempt used 'explicit-routing' and was clientbrand-specific the next one will be the next more-general, else it will be the same as "LIST"
#   "LIST" - if the last attempt used 'explicit-routing' the server-list will be used, else it will just go to the next server in the server-list
#   "DISCONNECT" - after the first routing failure the client will be kicked
routing-failure = ""

# Syntax
#   vX.X.X - game version
#   p000 - protocol version (Protocol Versions for every release/snapshot can be found here: https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Protocol_version_numbers)
#   cFORGE - Client brand (for example: vanilla, forge, fabric, geyser (for player joining through GeyserMC), badlion, lunarasdfasdfasdfasdf
# either a game version (v) or a protocol version (p) is necessary but client brands (c) are completely optional
# when no client brand is defined the routing just takes every client joining with the defined game/protocol version
[explicit-routing]
# Example: v1-21-8cFORGE = "lobby-1"
# Example: p123 = "lobby-2"
